name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Auth to dockerhub
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_ACCESS_TOKEN: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
      run: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_ACCESS_TOKEN}
    - name: Build the Docker image
      run: |
        c=1
        for i in $(cat releases)
        do
            if [ $c -eq 1 ];
            then
                docker build --rm --build-arg="OPENTTD_VERSION=$i" -t cipery/openttd:latest .
                docker push cipery/openttd:latest
                c=$((c+1))
            fi
            docker build --rm --build-arg="OPENTTD_VERSION=$i" -t cipery/openttd:$i .
            docker push cipery/openttd:$i
        done
